### ISSUE TITLE
BadRequest Error 400

### ISSUE THREAD

**Issue by MilkaPeeka** [inteoryx/twitter-video-dl#10]
So I try to run the script just as the example says ->
`$  python3 twitter-video-dl.py https://twitter.com/willowhalliwell/status/1452460936116244482 output`

Instead of downloading, this is what I get:

> Traceback (most recent call last):
>   File "/home/desktop/twitter-video-dl/twitter-video-dl.py", line 25, in <module>
>     tvdl.download_video(args.twitter_url, file_name)
>   File "/home/desktop/twitter-video-dl/src/twitter_video_dl/twitter_video_dl.py", line 139, in download_video
>     status_resp = send_request(
>   File "/home/desktop/twitter-video-dl/src/twitter_video_dl/twitter_video_dl.py", line 23, in send_request
>     assert response.status_code == 200, f"Failed request to {url}.  {response.status_code} {response_json}.  Please submit an issue including this information."
> AssertionError: Failed request to https://twitter.com/i/api/graphql/T0I8jIOz1Cfea00BjAXyfA/TweetDetail?variables=%7B%22focalTweetId%22%3A%221452460936116244482%22%2C%22with_rux_injections%22%3Afalse%2C%22includePromotedContent%22%3Atrue%2C%22withCommunity%22%3Atrue%2C%22withQuickPromoteEligibilityTweetFields%22%3Atrue%2C%22withBirdwatchNotes%22%3Afalse%2C%22withSuperFollowsUserFields%22%3Atrue%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%2C%22withSuperFollowsTweetFields%22%3Atrue%2C%22withVoice%22%3Atrue%2C%22withV2Timeline%22%3Atrue%7D&features=%7B%22dont_mention_me_view_api_enabled%22%3Atrue%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_uc_gql_enabled%22%3Afalse%2C%22responsive_web_edit_tweet_api_enabled%22%3Afalse%2C%22vibe_tweet_context_enabled%22%3Atrue%2C%22standardized_nudges_for_misinfo_nudges_enabled%22%3Afalse%7D.  400 {'errors': [{'message': 'The following features cannot be null: responsive_web_enhance_cards_enabled, standardized_nudges_misinfo', 'extensions': {'name': 'BadRequestError', 'source': 'Client', 'code': 336, 'kind': 'Validation', 'tracing': {'trace_id': '98a7322fba760064'}}, 'code': 336, 'kind': 'Validation', 'name': 'BadRequestError', 'source': 'Client', 'tracing': {'trace_id': '98a7322fba760064'}}]}.  Please submit an issue including this information.
>

**Comment by inteoryx** [comment]
Thank you for opening this issue.  Should be fixed by https://github.com/inteoryx/twitter-video-dl/commit/2943dd3c3e5396a8ccd53b997298a567d75c36c0  Please pull the latest and try again.  Thanks!

**Comment by MilkaPeeka** [comment]
Works beautifully, thank you!
