### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Chrisbadill** [inteoryx/twitter-video-dl#12]
assert query_id, f"Did not find query id.  Are you sure you used the right twitter URL? {video_url}"

**Comment by inteoryx** [comment]
Hmm, either I've forgotten how this works, or they've changed something.  This will take me a little while to fix.  Not sure when I'll have a chance to do it.  Maybe end of this week.

**Comment by DFMERA** [comment]
I'm getting the same error, the problem seems to be in this line:

src/twitter_video_dl.py
```
query_id = re.findall('queryId:"([^"]+)"', query_op[0])[0]
```

**Comment by ballchen** [comment]
It appears that the JavaScript file which previously included both the bearer token and the TweetDetail queryId no longer contains the TweetDetail queryId.

**Comment by prashant050701** [comment]
@inteoryx The problem seems to be the one mentioned by @ballchen.

**Comment by jperry004** [comment]
same problem here. I found that there's no queryId associated with any instance of TweetDetail in the json. I manually entered a queryId but then exploratory_request returns an empty string.

**Comment by inteoryx** [comment]
Should be working now.  Suggest you pull the latest and try again if you were hitting this.  The current state of the code is pretty brittle, just barely got this working.  Will clean it up a bit in coming days.
