### ISSUE TITLE
Wrong video downloaded

### ISSUE THREAD

**Issue by Perkinss27** [inteoryx/twitter-video-dl#15]
Hi,
while playing with your code, I figured out that for this specific [tweet](https://twitter.com/nocontexthumans/status/1641810447358631938) it wouldn't download the actual tweet video but the one from the first showed reply. 
My code :
`
tweet_url = "https://twitter.com/nocontexthumans/status/1641810447358631938"
`
`
tvdl.download_video(tweet_url, "tweetVideo2.mp4")
`

First frame of the tweet's video :

![scr1](https://user-images.githubusercontent.com/98915260/229294600-31cb4779-eb79-45e2-9ac6-76f30afc9eee.png)

First frame of the downloaded video :

![scr2](https://user-images.githubusercontent.com/98915260/229294594-965331d0-3c59-4129-b913-5b9c2fda11ca.png)

If you have some free time, please try to replicate this bug on your side to see if it's unique to my setup or if it's a global bug.

Thank you for keeping this repo alive.

### EDIT 1 : 
I guess that I am the one wrong here. It looks like the author of the tweet I sent earlier just "reposted" a video and did not post it directly to twitter through its account as we can see here :

![](https://user-images.githubusercontent.com/98915260/229296085-4008ff6f-8b32-4f21-ad97-e2f2d7bbf2f5.png)

It could be a cool feature to download videos in such cases though, because we do not always think to open the original video's tweet.

### EDIT 2 : 
So I wasn't totally wrong because I found this [tweet ](https://twitter.com/StrangestMedia/status/1641086559037579264/)while trying to code a solution.
This tweet still cause the bug to occur, even if it's not a repost.
It still downloads the first showed video in the replies but this tweet's video isn't reposted.
As you can see both tweets feature the same video (the first one is a repost) because my solution to this bug was to extract the url of the source tweet (that contain the non reposted video) and then to send it back to the download_video function, so I could get the video, even from a reposted tweet.

### EDIT 3 :
The bug actually come from the `extract_mp4s` function. Your `ext_tw_pattern` regular expression actually find the video url, but
the function automatically returns container urls if it find some : 
![scr222](https://user-images.githubusercontent.com/98915260/229344745-73c487ac-87f9-4d4b-b012-3d29674d201f.png)

It then skips any other video url, which in my case include the one I want.
In fact, in this [tweet ](https://twitter.com/StrangestMedia/status/1641086559037579264/) case the tweet video url is :
`https://video.twimg.com/ext_tw_video/1641074057524174848/pu/vid/404x720/YvImuEf6bgC5P9jl.mp4?tag=12`
While the first showed video in the replies has this url :
`https://video.twimg.com/ext_tw_video/1634237199096123392/pu/pl/ig4YOUAgpgyowlbd.m3u8?tag=12&container=fmp4`

Given that it's a container url, `extract_mp4s` directly returns this video link which causes this bug.

**Comment by Perkinss27** [comment]
I guess that I am the one wrong here. It looks like the author of the tweet I sent earlier just "reposted" a video and did not post it directly to twitter through its account as we can see here :

![image](https://user-images.githubusercontent.com/98915260/229296085-4008ff6f-8b32-4f21-ad97-e2f2d7bbf2f5.png)

It could be a cool feature to download videos in such cases though, because we do not always think to open the original video's tweet.

**Comment by Perkinss27** [comment]
So I'm not totally wrong because I found this [tweet ](https://twitter.com/StrangestMedia/status/1641086559037579264/)while trying to code a solution. 
This tweet still cause the bug to occur, even if it's not a repost.
It still downloads the first showed video in the replies but this video isn't reposted. 
As you can see both tweets feature the same video (the frist one is a report) because my solution to this was to extract the url of the source tweet (that contain the non reposted video) and then send it back to the download_video function, so i could get the video, even from a reposted tweet.

**Comment by Perkinss27** [comment]
I'm working on a fix, I'll share it here later this day or tomorrow.

**Comment by Perkinss27** [comment]
Fix [commited ](https://github.com/Perkinss27/twitter-video-dl/commit/1428e400ce7ef5a7b8dcd9a6e9e98dded6bb1159)to my fork. 
Code might be messy, and we might have to do further checking before assuming it works correctly.
It's an early fix that worked for the case I explained earlier.
For more details about what's modified and what's added please read my [comment](https://github.com/Perkinss27/twitter-video-dl/commit/1428e400ce7ef5a7b8dcd9a6e9e98dded6bb1159#commitcomment-107297313).

**Comment by inteoryx** [comment]
Awesome, thanks very much for finding this issue and submitting a fix.  There is an issue with your fix which is that it can download lower resolution than the max available, for example try your code with https://twitter.com/Queen__Deshda/status/1452467693517426697 - it downloads a lower resolution version of the video than the mainline.  Ideally I would like to keep the max resolution behavior.

When I have a chance I will try to update your code to keep the max resolution version and merge it.  Or, if you want to take that on, that would be great.  From the tests directory you can run "python TestVideoDownloader.py" and it will catch errors like this.

I really do appreciate your PR and will merge it soon once this issue is ironed out - thanks again.

**Comment by inteoryx** [comment]
Thank you very much for all this.  Excellent bug report and, even better, it came with a fix.  I have pulled in your fix and updated the test cases file.  Seems to all be working now.  I really appreciate your contribution.
