### ISSUE TITLE
Does not work with links that have &

### ISSUE THREAD

**Issue by yarodevuci** [inteoryx/twitter-video-dl#17]
twitter-video-dl.py https://twitter.com/jackposobiec/status/1644904637810573312?s=46&t=C4RATVnzrLTKmtxPwRNPQQ temp

The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.

@inteoryx

**Comment by yarodevuci** [comment]
could not get status id from this tweet url

**Comment by yarodevuci** [comment]
I guess i have to manually trim the url and remove everything after status id

**Comment by inteoryx** [comment]
Should be fixed now.  Please pull the latest and try again.  Status id regex wasn't matching urls with query parameters.

**Comment by yarodevuci** [comment]
awesome, thanks
