### ISSUE TITLE
Not working 400

### ISSUE THREAD

**Issue by diegooviedo3004** [inteoryx/twitter-video-dl#2]
AssertionError: Failed request to https://twitter.com/i/api/graphql/sPFwumWnbdt7IpB6a9krVQ/TweetDetail?variables=%7B%22focalTweetId%22%3A%221452460936116244482%22%2C%22with_rux_injections%22%3Afalse%2C%22includePromotedContent%22%3Atrue%2C%22withCommunity%22%3Atrue%2C%22withQuickPromoteEligibilityTweetFields%22%3Afalse%2C%22withTweetQuoteCount%22%3Atrue%2C%22withBirdwatchNotes%22%3Afalse%2C%22withSuperFollowsUserFields%22%3Atrue%2C%22withUserResults%22%3Atrue%2C%22withNftAvatar%22%3Afalse%2C%22withBirdwatchPivots%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%2C%22withSuperFollowsTweetFields%22%3Atrue%2C%22withVoice%22%3Atrue%7D.  400.  Please submit an issue including this information.

**Comment by inteoryx** [comment]
Thanks for the report.  Just pushed a fix.  Should be working now.
