### ISSUE TITLE
Downloaded videos don't play

### ISSUE THREAD

**Issue by raphsilva** [inteoryx/twitter-video-dl#3]
I tried to download some videos from the examples in the repo, but the saved MP4 doesn't play. 
Even FFmpeg can't read it, it says: 
```
$ ffmpeg -i output_file_name.mp4 a.mp4
ffmpeg version git-2020-07-25-7c8ad72 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --enable-nonfree --enable-cuda-nvcc --enable-libnpp --enable-gpl --enable-libx264 --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64
  libavutil      56. 57.100 / 56. 57.100
  libavcodec     58. 97.102 / 58. 97.102
  libavformat    58. 49.100 / 58. 49.100
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x56196acbedc0] could not find corresponding trex (id 1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x56196acbedc0] could not find corresponding track id 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x56196acbedc0] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x56196acbedc0] error reading header
output_file_name.mp4: Invalid data found when processing input
```

**Comment by inteoryx** [comment]
Thank you for the report.  I was able to reproduce this issue.

It seems Twitter added a query parameter to the MP4 container URL that was messing up a regex of mine.  I have updated the script in question.  I used the script to download all of the videos in the test file and was able to play them all in VLC.  I then did your ffmpeg command and that was successful as well.

Please pull the latest changes and try again on your end.  If it is now working then kindly close this issue.  If not, leave a comment.  If you have not closed or responded to the issue within three days I will close it as fixed.

Thanks!

**Comment by raphsilva** [comment]
Very nice work, thanks a lot!!
