### ISSUE TITLE
Downloaded video is split and out of order

### ISSUE THREAD

**Issue by raphsilva** [inteoryx/twitter-video-dl#4]
When trying to download one of the example videos `python3.8 twitter-video-dl.py https://twitter.com/crabcrawler1/status/1460400562176987145 output_file_name`, the output comes in four parts, and they are not in the correct order of the original video.

**Comment by inteoryx** [comment]
@raphsilva Should be fixed now.

Took a fair bit of refactoring.  My previous method just downloaded all associated videos because there are many ways for a video to be posted.  I think this will work correctly now.  It at least works in all cases in the test_videos file.
