### ISSUE TITLE
Thanks for your library

### ISSUE THREAD

**Issue by parvij** [inteoryx/twitter-video-dl#6]
Reloaded modules: dl_video.twitter_video_dl, dl_video.twitter_video_dl.twitter_video_dl
Traceback (most recent call last):

  File "C:\Users\..\Twitter Project\download_videos.py", line 14, in <module>
    tvdl.download_video('https://twitter.com/willowhalliwell/status/1452460936116244482', '1522952577809223681.mp4')

  File "C:\Users\..\Twitter Project\dl_video\twitter_video_dl\twitter_video_dl.py", line 104, in download_video
    f"{STATUS_ENDPOINT}{query_id}/{status_params}", session.get, headers)

  File "C:\Users\..\Twitter Project\dl_video\twitter_video_dl\twitter_video_dl.py", line 17, in send_request
    assert response.status_code == 200, f"Failed request to {url}.  {response.status_code}.  Please submit an issue including this information."

AssertionError: Failed request to https://twitter.com/i/api/graphql/GKajRJ_uQ1wdg6Zs0xvIuA/TweetDetail?variables=%7B%22focalTweetId%22%3A%221452460936116244482%22%2C%22with_rux_injections%22%3Afalse%2C%22includePromotedContent%22%3Atrue%2C%22withCommunity%22%3Atrue%2C%22withQuickPromoteEligibilityTweetFields%22%3Afalse%2C%22withTweetQuoteCount%22%3Atrue%2C%22withBirdwatchNotes%22%3Afalse%2C%22withSuperFollowsUserFields%22%3Atrue%2C%22withUserResults%22%3Atrue%2C%22withNftAvatar%22%3Afalse%2C%22withBirdwatchPivots%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%2C%22withSuperFollowsTweetFields%22%3Atrue%2C%22withVoice%22%3Atrue%2C%22withDownvotePerspective%22%3Afalse%7D.  400.  Please submit an issue including this information.

**Comment by inteoryx** [comment]
Thank you for filing this issue.  Just checked my email and saw it.  Fix is in now and all the tests are working for me.  Please pull the latest and try again.  Let me know if you still have issues.
