### ISSUE TITLE
Automatic download 

### ISSUE THREAD

**Issue by FevLoad** [inteoryx/twitter-video-dl#8]
Jello there
Want to ask would it be possible to get this script work in loop monitoring users list and any new tweet contain a video from anyone name/user on the list the script will download that video
In downloads folder in this format
/home/downloads/usernick/video file - dated-ext

Thanks and hope this suggestion catch your eyes and made a road map to do it

**Comment by inteoryx** [comment]
Hi, thanks for your question.

First, I don't expect to add this feature to this project.  I intend this project to provide one specific bit of functionality - that is, to download a video from a tweet.  An automated video downloader seems like it might be a useful thing, but it is not the purpose of this project.

Second, this project is nearly ready / able to become a library that could be installed via pip.  Once that is done I think this project could be a useful component of an automated video downloader that I see you describing.

Third, how I would approach your idea is: get a list of the user's tweets, check the metadata of each tweet to see if it contains a video, if the tweet does contain a video then supply it to twitter-video-dl.

Finally, if you want to take this on and ask me questions about using this project as a library, feel free (email inteoryx at protonmail dot com).  Likewise contact me if you think money might be involved in any way.  For example, if you wanted the automated twitter video download thing as a part of a project that might make money - then I could definitely help out / get this done quite quickly.   Other than that, I hope I've addressed your question.

Thanks!
