### ISSUE TITLE
Response code 400

### ISSUE THREAD

**Issue by fosamil** [inteoryx/twitter-video-dl#9]
AssertionError: Failed request to https://twitter.com/i/api/graphql/iXunlAxclfRgknK8bnaMvA/TweetDetail?variables=%7B%22focalTweetId%22%3A%221451361961782906889%22%2C%22with_rux_injections%22%3Afalse%2C%22includePromotedContent%22%3Atrue%2C%22withCommunity%22%3Atrue%2C%22withQuickPromoteEligibilityTweetFields%22%3Atrue%2C%22withBirdwatchNotes%22%3Afalse%2C%22withSuperFollowsUserFields%22%3Atrue%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%2C%22withSuperFollowsTweetFields%22%3Atrue%2C%22withVoice%22%3Atrue%2C%22withV2Timeline%22%3Atrue%7D&features=%7B%22dont_mention_me_view_api_enabled%22%3Atrue%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_uc_gql_enabled%22%3Afalse%2C%22responsive_web_edit_tweet_api_enabled%22%3Afalse%2C%22vibe_tweet_context_enabled%22%3Atrue%7D.  400 {'errors': [{'message': 'The following features cannot be null: standardized_nudges_for_misinfo_nudges_enabled', 'extensions': {'name': 'BadRequestError', 'source': 'Client', 'code': 336, 'kind': 'Validation', 'tracing': {'trace_id': '2999ea54e07c1fc3'}}, 'code': 336, 'kind': 'Validation', 'name': 'BadRequestError', 'source': 'Client', 'tracing': {'trace_id': '2999ea54e07c1fc3'}}]}.

This happens regardless of which video I try. Is it just me?

**Comment by fosamil** [comment]
I fixed this by adding "standardized_nudges_for_misinfo_nudges_enabled" as False in json_features. False is the value sent when accessed with the browser.

**Comment by inteoryx** [comment]
This is indeed a bug.  Looks like your solution is the right one.  Thanks for leaving this comment.  In the future it would be even better to send a PR with the fix.

**Comment by inteoryx** [comment]
Fixed with 61f88588e4b5566b590642e6277ab236916da581
